tethered_turtle_sim:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

  # Position Controllers ---------------------------------------
  turtle1/wheel_left_joint_controller: 
    type: effort_controllers/JointEffortController
    joint: turtle1/wheel_left_joint
    pid: {p: 100.0, i: 5.0, d: 10.0}

  turtle1/wheel_right_joint_controller: 
    type: effort_controllers/JointEffortController
    joint: turtle1/wheel_right_joint
    pid: {p: 100.0, i: 5.0, d: 10.0}

  turtle2/wheel_left_joint_controller: 
    type: effort_controllers/JointEffortController
    joint: turtle2/wheel_left_joint
    pid: {p: 100.0, i: 5.0, d: 10.0}

  turtle2/wheel_right_joint_controller: 
    type: effort_controllers/JointEffortController
    joint: turtle2/wheel_right_joint
    pid: {p: 100.0, i: 5.0, d: 10.0}





